spring.application.name=SpringJDBCEx

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/demo
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# Run schema.sql / data.sql against PostgreSQL (default is embedded DBs only)
spring.sql.init.mode=always
